abd_features_1 = ['pain_mention_Previous_note', 
                  'Pain_Value_Master', 
                  'pain_mention_Interval_History', 
                  'pain_mentions_remaining_keywords', 
                  'well_mention_keyword', 
                  'pain_mentions', 
                  'Pain_Present_HPI', 
                  'dia_mentions_HPI_keywords', 
                  'pain_mention_keyword', 
                  'pain_mentions_HPI', 
                  'blood_mentions_HPI', 
                  'stool_fre_mentions_HPI', 
                  'Stool_fre_Master', 
                  'pain_mention_HPI', 
                  'Dia_Master', 
                  'Diarrhea_Present']

abd_features_2 = ['Pain_Value_Master', 
                  'Pain_Present_HPI', 
                  'Pain_Present', 
                  'pain_mention_Previous_note', 
                  'well_mentions', 
                  'cr_mention_Previous_note', 
                  'blood_mentions', 
                  'stool_fre_mentions', 
                  'Diarrhea_Present', 
                  'dia_mention_Previous_note', 
                  'CR_Master', 
                  'pain_mentions_HPI', 
                  'well_mention_keyword', 
                  'stool_fre_mentions_HPI', 
                  'pain_mentions', 
                  'cr_mention_HPI_keyword', 
                  'cr_mention_keyword', 
                  'blood_mentions_HPI', 
                  'blood_mention_Previous_note', 
                  'Current_Extract', 
                  'dia_mention_remaining_notes', 
                  'Well_Present_HPI', 
                  'blood_mentions_remaining_keywords', 
                  'stool_fre_mention_Previous_note', 
                  'well_mentions_HPI', 
                  'pain_mentions_remaining_keywords', 
                  'stool_range_Present', 
                  'pain_mention_Interval_History', 
                  'dia_mentions_HPI_keywords']

diarrhea_features_1 = ['stool_fre_mention_remaining_notes', 
                       'Well_Present_HPI', 
                       'CR_mention_Interval_History', 
                       'stool_fre_mention_Interval_History', 
                       'Dia_Master', 
                       'dia_mention_Interval_History', 
                       'blood_mention_keyword', 
                       'well_mention_Interval_History', 
                       'dia_mention_remaining_notes', 
                       'Fecal_Blood_Present', 
                       'stool_fre_mentions_HPI', 
                       'stool_fre_mention_Previous_note', 
                       'Stool_fre_Master', 
                       'blood_mention_Previous_note', 
                       'Dia_Present_Remaining', 
                       'Fecal_Blood_Value_Master', 
                       'well_mentions', 
                       'blood_mentions', 
                       'pain_mentions', 
                       'ROS_Valid', 
                       'CR_mention_Previous_note', 
                       'well_mentions_HPI', 
                       'well_mention_Previous_note', 
                       'pain_mention_HPI', 
                       'Fecal_Blood_Present_HPI', 
                       'cr_mentions_HPI', 
                       'blood_mention_Interval_History', 
                       'well_mention_HPI_keyword', 
                       'stool_range_Present']

diarrhea_features_2 = ['Well_Present', 
                       'stool_range_Present', 
                       'stool_fre_mentions', 
                       'blood_mentions_HPI', 
                       'pain_mentions', 
                       'Stool_fre_Master', 
                       'Fecal_Blood_Value_Master', 
                       'Fecal_Blood_Present_HPI', 
                       'stool_fre_mention_remaining_notes', 
                       'pain_mention_Previous_note', 
                       'well_mentions_HPI', 
                       'cr_mentions_HPI', 
                       'dia_mentions_HPI_keywords', 
                       'pain_mention_HPI', 
                       'dia_mentions', 
                       'Dia_Master', 
                       'stool_fre_mention_Interval_History', 
                       'well_mention_keyword', 
                       'stool_fre_mention_Previous_note', 
                       'stool_fre_mentions_HPI', 
                       'cr_mention_HPI', 
                       'Dia_Present_Remaining', 
                       'dia_mentions_HPI', 
                       'well_mentions', 
                       'ROS_Valid', 
                       'pain_mentions_remaining_keywords', 
                       'blood_mention_HPI', 
                       'dia_mention_Previous_note', 
                       'blood_mention_keyword']

def map2int(x):
    if type(x) == str:
        return 1
    if type(x) == list:
        return len(x)
    if type(x) == bool:
        return int(x)
    else:
        return x